### ISSUE TITLE
how i can setup this in a website

### ISSUE THREAD

**Issue by ghost** [MrSprinkleToes/roblox-in-webbrowser#1]

**Comment by MrSprinkleToes** [comment]
Run the cors.js and index.js files on your system with nodejs and then open the rbxl file, publish the place so that it can use HttpService, then play the game. You should be able to view it in the web browser at 127.0.0.1:3000.

**Comment by ghost** [comment]
thanks

**Comment by ghost** [comment]
a friend setup this using ngrok! this is nice
